const BASE='https://resultados.tse.jus.br';
const memory=new Map<string,{data:any;at:number}>();const inflight=new Map<string,Promise<any>>();
export const states=[['ac','Acre','Norte'],['al','Alagoas','Nordeste'],['ap','Amapá','Norte'],['am','Amazonas','Norte'],['ba','Bahia','Nordeste'],['ce','Ceará','Nordeste'],['df','Distrito Federal','Centro-Oeste'],['es','Espírito Santo','Sudeste'],['go','Goiás','Centro-Oeste'],['ma','Maranhão','Nordeste'],['mt','Mato Grosso','Centro-Oeste'],['ms','Mato Grosso do Sul','Centro-Oeste'],['mg','Minas Gerais','Sudeste'],['pa','Pará','Norte'],['pb','Paraíba','Nordeste'],['pr','Paraná','Sul'],['pe','Pernambuco','Nordeste'],['pi','Piauí','Nordeste'],['rj','Rio de Janeiro','Sudeste'],['rn','Rio Grande do Norte','Nordeste'],['rs','Rio Grande do Sul','Sul'],['ro','Rondônia','Norte'],['rr','Roraima','Norte'],['sc','Santa Catarina','Sul'],['sp','São Paulo','Sudeste'],['se','Sergipe','Nordeste'],['to','Tocantins','Norte']].map(([uf,name,region])=>({uf,name,region}));
export const slug=(s:string)=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const title=(s:string)=>s.toLocaleLowerCase('pt-BR').replace(/(^|[\s-])\p{L}/gu,c=>c.toLocaleUpperCase('pt-BR'));
const num=(v:unknown):number|null=>v==null||v===''?null:Number.isFinite(Number(String(v).replace(',','.')))?Number(String(v).replace(',','.')):null;
const timestamp=(d:string,h:string)=>d&&h?`${d.split('/').reverse().join('-')}T${h}-03:00`:'';
export async function raw(path:string,ttl=20000):Promise<{data:any;stale:boolean}>{const old=memory.get(path);if(old&&Date.now()-old.at<ttl)return{data:old.data,stale:false};if(inflight.has(path))return inflight.get(path)!;const work=(async()=>{try{const r=await fetch(BASE+path,{signal:AbortSignal.timeout(16000),headers:{Accept:'application/json'}});if(!r.ok)throw new Error(`Fonte indisponível (${r.status})`);const data=await r.json() as any;if(data.f!=='o')throw new Error('Arquivo não oficial rejeitado');if(memory.size>2500)memory.delete(memory.keys().next().value!);memory.set(path,{data,at:Date.now()});return{data,stale:false}}catch(e){if(old)return{data:old.data,stale:true};throw e}finally{inflight.delete(path)}})();inflight.set(path,work);return work}
async function config(office:string){const {data}=await raw('/oficial/comum/config/ele-c.json',3600000);const pl=data.pl.find((p:any)=>p.c==='ele2026'&&p.dt==='04/10/2026');const ele=pl?.e.find((e:any)=>e.t==='1'&&e.abr.some((a:any)=>a.cp?.some((c:any)=>String(c.cd)===office)));if(!ele)throw new Error('Configuração oficial de 2026 indisponível');return{cycle:pl.c,id:ele.cd,padded:String(ele.cd).padStart(6,'0'),dirs:data.arq}}
function directory(cfg:any,type:string,uf:string){const template=cfg.dirs.find((d:any)=>d.tp===type)?.dir;if(!template)throw new Error('Diretório não informado pelo TSE');const path=template.replace('<base>',BASE).replace('<ambiente>','oficial').replace('<ciclo>',cfg.cycle).replace('<cd_eleicao>',cfg.id).replace('<uf>',uf);if(!path.startsWith(BASE+'/oficial/ele2026/'))throw new Error('Diretório inválido');return path.slice(BASE.length)}
export async function locations(){const cfg=await config('1');const {data}=await raw(`${directory(cfg,'cm','br')}/mun-e${cfg.padded}-cm.json`,3600000);return{states,cities:data.abr.filter((a:any)=>states.some(s=>s.uf===a.cd)).flatMap((a:any)=>a.mu.map((m:any)=>({uf:a.cd,code:String(m.cd).padStart(5,'0'),name:title(m.nm),slug:slug(m.nm),capital:m.c==='s'})))}}
export async function result(uf='br',city:string|null=null,office='1'){if(uf!=='br'&&!states.some(s=>s.uf===uf))throw new Error('Estado não encontrado');if(!['1','3','5','6','7','8'].includes(office)||uf==='br'&&office!=='1'||uf==='df'&&office==='7'||uf!=='df'&&office==='8')throw new Error('Cargo indisponível nesta abrangência');const cfg=await config(office);let code='';if(city){const list=await locations();const found=list.cities.find((m:any)=>m.uf===uf&&(m.slug===city||m.code===city));if(!found)throw new Error('Município não encontrado');code=found.code}const path=`${directory(cfg,'u',uf)}/${uf}${code}-c${office.padStart(4,'0')}-e${cfg.padded}-u.json`;const{data:d,stale}=await raw(path);if(String(d.ele)!==String(cfg.id)||String(d.t)!=='1')throw new Error('Eleição divergente');const disclosed=d.dv==='s';const officeData=d.carg?.find((c:any)=>String(c.cd)===office);if(!officeData||!d.s||!d.e||!d.v)throw new Error('Formato oficial inesperado');const candidates=officeData.agr.flatMap((a:any)=>a.par.flatMap((p:any)=>p.cand.map((c:any)=>({id:c.sqcand,name:title(c.nmu||c.nm),fullName:title(c.nm),number:c.n,party:p.sg,votes:disclosed?num(c.vap):null,percent:disclosed?num(c.pvap):null,status:c.st||(d.and==='f'?'Sem situação informada':'Em apuração'),destination:c.dvt,office,uf:office==='1'?'br':uf,photo:BASE+directory(cfg,'ft',office==='1'?'br':uf)+'/'+c.sqcand+'.jpeg'})))).sort((a:any,b:any)=>(b.votes??0)-(a.votes??0));const safe=(v:unknown)=>disclosed?num(v):null;return{uf,city,office,source:BASE+path,updatedAt:timestamp(d.dt||d.dg,d.ht||d.hg),generatedAt:timestamp(d.dg,d.hg),fetchedAt:new Date().toISOString(),generation:d.idg,stale,finished:d.and==='f',disclosed,candidates,stats:{sections:num(d.s.st),totalSections:num(d.s.ts),progress:num(d.s.pst),electorate:num(d.e.te),attendance:safe(d.e.c),attendancePercent:safe(d.e.pc),abstentions:safe(d.e.a),abstentionPercent:safe(d.e.pa),valid:safe(d.v.vvc),blank:safe(d.v.vb),blankPercent:safe(d.v.pvb),null:safe(d.v.tvn),nullPercent:safe(d.v.ptvn)}}}
async function pool<T,R>(items:T[],fn:(x:T)=>Promise<R>,n=4){const out:R[]=[];let cursor=0;await Promise.all(Array.from({length:n},async()=>{while(cursor<items.length){const i=cursor++;out[i]=await fn(items[i])}}));return out}
export async function stateSummary(){return pool(states,async s=>{try{const r=await result(s.uf);return{...s,progress:r.stats.progress,leader:r.disclosed?r.candidates[0]??null:null,updatedAt:r.updatedAt}}catch{return{...s,progress:null,leader:null,error:true}}})}
export async function cities(uf:string,office='1'){const loc=await locations();const list=loc.cities.filter((c:any)=>c.uf===uf);if(!list.length)return[];try{const cfg=await config(office);const{data}=await raw(`${directory(cfg,'ab',uf)}/${uf}-e${cfg.padded}-ab.json`);return list.map((city:any)=>{const info=data.abr?.find((a:any)=>a.tpabr!=='uf'&&String(a.cdabr).padStart(5,'0')===city.code);return{...city,electorate:num(info?.e?.te),progress:num(info?.s?.pst)}})}catch{return list}}

export async function candidateIndex(uf:string){const offices=uf==='df'?['3','5','6','8']:['3','5','6','7'];const data=await Promise.all(offices.map(o=>result(uf,null,o)));return data.flatMap(d=>d.candidates)}
